
import { supabase } from './supabase.js'
import './style.css'

const app=document.querySelector('#app')
let user=null,db={studies:[],hands:[],results:[],goals:[]},currentPage='dashboard',periodDays=30
const esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))
const money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'})
const pct=(a,b)=>b?((a/b)*100).toFixed(1)+'%':'0.0%'
const today=()=>new Date().toISOString().slice(0,10)
const tagList=s=>String(s||'').split(',').map(x=>x.trim()).filter(Boolean)

function loginView(){
 app.innerHTML=`<main class="auth"><div class="authbox"><div class="brand">Poker <b>Study</b><small>V3 • PERFORMANCE HUB</small></div>
 <h1>Entrar</h1><p class="muted">Estudos, mãos e resultados sincronizados na nuvem.</p>
 <input id="email" type="email" placeholder="E-mail"><input id="password" type="password" placeholder="Senha">
 <button class="btn" id="signin">Entrar</button><button class="btn secondary" id="signup">Criar conta</button><p id="msg" class="muted"></p></div></main>`
 signin.onclick=async()=>{const {error}=await supabase.auth.signInWithPassword({email:email.value.trim(),password:password.value});msg.textContent=error?error.message:''}
 signup.onclick=async()=>{if(!email.value.trim()||!password.value)return msg.textContent='Preencha e-mail e senha.';const {error}=await supabase.auth.signUp({email:email.value.trim(),password:password.value});msg.textContent=error?error.message:'Conta criada. Verifique seu e-mail se necessário.'}
}
async function load(){
 for(const t of ['studies','hands','results','goals']){const {data,error}=await supabase.from(t).select('*').order('date',{ascending:false});db[t]=error?[]:(data||[])}
 for(const h of db.hands){h.image_url='';if(h.image_path){const {data}=await supabase.storage.from('hand-images').createSignedUrl(h.image_path,3600);h.image_url=data?.signedUrl||''}}
}
function shell(){
 app.innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">Poker <b>Study</b><small>V3 • CLOUD</small></div><nav class="nav">
 ${[['dashboard','📊 Dashboard'],['studies','📚 Estudos'],['hands','🖐️ Mãos'],['results','💰 Resultados'],['leaks','🧠 Leaks'],['goals','🎯 Metas'],['reports','📈 Relatórios']].map(([p,l])=>`<button data-p="${p}">${l}</button>`).join('')}
 </nav><button class="btn logout" id="logout">Sair</button></aside><main class="content"><header><div class="header-title"><h1 id="title"></h1><div class="muted" id="subtitle"></div></div><span class="user">${esc(user.email)}</span></header><section id="page"></section></main></div>
 <div id="modal" class="modal"><div class="modal-box"><div class="modal-head"><h2 id="modalTitle"></h2><button class="btn secondary" id="closeModal">Fechar</button></div><div id="modalBody"></div></div></div>`
 document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>route(b.dataset.p));logout.onclick=async()=>await supabase.auth.signOut();closeModal.onclick=()=>modal.classList.remove('show');route(currentPage)
}
function route(p){
 currentPage=p;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===p))
 const meta={dashboard:['Dashboard','Visão geral de performance e estudo'],studies:['Estudos','Aulas, cursos, progresso e tags'],hands:['Banco de mãos','Mãos, imagens, análise e revisão'],results:['Resultados','Sessões, sites e formatos'],leaks:['Leaks','Prioridades baseadas nas suas marcações'],goals:['Metas','Objetivos de volume e estudo'],reports:['Relatórios','Leitura consolidada dos dados']}[p]
 title.textContent=meta[0];subtitle.textContent=meta[1];page.innerHTML=({dashboard,studies,hands,results,leaks,goals,reports})[p]();bindPage(p)
}
function filteredResults(){if(!periodDays)return db.results;const d=new Date();d.setDate(d.getDate()-periodDays);return db.results.filter(x=>new Date(x.date)>=d)}
function dashboard(){
 const r=filteredResults(),g=r.reduce((a,x)=>a+(+x.tournaments||0),0),bi=r.reduce((a,x)=>a+(+x.buyins||0),0),p=r.reduce((a,x)=>a+(+x.profit||0),0),itm=r.reduce((a,x)=>a+(+x.itm||0),0),studyH=db.studies.filter(x=>x.status==='done').reduce((a,x)=>a+(+x.duration||0),0)/60
 const s=[...r].sort((a,b)=>a.date.localeCompare(b.date)).slice(-20),mx=Math.max(1,...s.map(x=>Math.abs(+x.profit||0)))
 const chart=s.length?s.map(x=>`<div class="chart-col" title="${x.date}: ${money(x.profit)}"><i style="height:${Math.max(3,Math.abs(x.profit)/mx*88)}%;opacity:${x.profit<0?.45:1}"></i><span>${x.date.slice(5)}</span></div>`).join(''):'<p class="muted">Sem resultados no período.</p>'
 return `<div class="toolbar"><select id="periodSelect" style="width:auto"><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="0">Tudo</option></select></div>
 <div class="cards">${[['Torneios',g],['ABI',money(g?bi/g:0)],['Profit',money(p)],['ROI',pct(p,bi)],['ITM',pct(itm,g)],['Estudo',studyH.toFixed(1)+'h']].map((x,i)=>`<div class="card"><small>${x[0]}</small><strong class="${i===2?(p>=0?'good':'bad'):''}">${x[1]}</strong></div>`).join('')}</div>
 <div class="grid2"><div class="panel"><h2>Profit por dia</h2><div class="chart">${chart}</div></div><div class="panel"><h2>Fila de revisão</h2>${db.hands.filter(x=>x.status!=='done').slice(0,6).map(h=>`<div class="item"><b>${esc(h.topic||'Geral')}</b> · ${esc(h.spot||'')}<br><span class="muted">${esc(h.question||'')}</span></div>`).join('')||'<p class="muted">Nenhuma mão pendente.</p>'}</div></div>`
}
function studies(){return `<div class="toolbar"><button class="btn" id="newStudy">+ Nova aula</button></div><div class="panel">${db.studies.length?`<table><tr><th>Curso / Aula</th><th>Tema</th><th>Professor</th><th>Duração</th><th>Data</th><th>Status</th><th></th></tr>${db.studies.map(x=>`<tr><td><b>${esc(x.course||'')}</b>${x.course?'<br>':''}${esc(x.title)}</td><td>${esc(x.topic||'Geral')}<br>${tagList(x.tags).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</td><td>${esc(x.teacher||'')}</td><td>${x.duration||0} min</td><td>${x.date}</td><td><span class="pill ${x.status==='done'?'good':'warn'}">${x.status==='done'?'Assistida':'Pendente'}</span></td><td><button class="btn small secondary" data-toggle-study="${x.id}">Alternar</button></td></tr>`).join('')}</table>`:'<p class="muted">Nenhuma aula.</p>'}</div>`}
function hands(){return `<div class="toolbar"><button class="btn" id="newHand">+ Nova mão</button></div><div class="hand-grid">${db.hands.length?db.hands.map(h=>`<article class="hand-card">${h.image_url?`<img src="${h.image_url}" alt="Imagem da mão">`:`<div style="aspect-ratio:16/9;display:grid;place-items:center;background:#0c1526;color:#64748b">Sem imagem</div>`}<div class="hand-body"><h3>${esc(h.tournament||'Mão sem torneio')}</h3><div class="muted">${h.date} · ${esc(h.site||'')} · ${esc(h.format||'')}</div><p><b>${esc(h.spot||'Spot')}</b> · ${esc(h.topic||'Geral')}</p><p>${esc(h.question||'')}</p><div>${tagList(h.tags).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="toolbar" style="margin-top:10px"><button class="btn small secondary" data-view-hand="${h.id}">Ver detalhes</button><button class="btn small" data-toggle-hand="${h.id}">${h.status==='done'?'Reabrir':'Marcar estudada'}</button></div></div></article>`).join(''):'<p class="muted">Nenhuma mão cadastrada.</p>'}</div>`}
function results(){return `<div class="toolbar"><button class="btn" id="newResult">+ Novo resultado</button></div><div class="panel">${db.results.length?`<table><tr><th>Data</th><th>Site</th><th>Formato</th><th>MTTs</th><th>ABI</th><th>Buy-ins</th><th>Prêmios</th><th>Profit</th><th>ROI</th><th>Horas</th></tr>${db.results.map(x=>`<tr><td>${x.date}</td><td>${esc(x.site||'')}</td><td>${esc(x.format||'')}</td><td>${x.tournaments}</td><td>${money(x.abi)}</td><td>${money(x.buyins)}</td><td>${money(x.prizes)}</td><td class="${x.profit>=0?'good':'bad'}"><b>${money(x.profit)}</b></td><td>${pct(x.profit,x.buyins)}</td><td>${x.hours||0}</td></tr>`).join('')}</table>`:'<p class="muted">Nenhum resultado.</p>'}</div>`}
function leakData(){const m={};for(const h of db.hands){for(const k of [h.topic,...tagList(h.tags)].filter(Boolean)){if(!m[k])m[k]={hands:0,pending:0,studies:0};m[k].hands++;if(h.status!=='done')m[k].pending++}}for(const s of db.studies){for(const k of [s.topic,...tagList(s.tags)].filter(Boolean)){if(!m[k])m[k]={hands:0,pending:0,studies:0};if(s.status==='done')m[k].studies++}}return Object.entries(m).map(([topic,v])=>({topic,...v,score:v.pending*3+v.hands-Math.min(v.studies,5)})).sort((a,b)=>b.score-a.score)}
function leaks(){const a=leakData();return `<div class="grid3">${a.length?a.map((x,i)=>`<div class="card"><small>${i<2?'PRIORIDADE ALTA':'TEMA'}</small><strong>${esc(x.topic)}</strong><p class="muted">${x.hands} mãos · ${x.pending} pendentes · ${x.studies} aulas</p><div class="progress"><i style="width:${Math.min(100,x.pending*15+x.hands*3)}%"></i></div></div>`).join(''):'<div class="panel"><p class="muted">Cadastre temas e tags para gerar leaks.</p></div>'}</div>`}
function goals(){return `<div class="toolbar"><button class="btn" id="newGoal">+ Nova meta</button></div><div class="grid3">${db.goals.length?db.goals.map(g=>`<div class="card"><small>${esc(g.metric||'META')}</small><strong>${esc(g.title)}</strong><p class="muted">${g.current_value||0} / ${g.target_value||0} ${esc(g.unit||'')}</p><div class="progress"><i style="width:${Math.min(100,(+g.current_value||0)/(+g.target_value||1)*100)}%"></i></div><div class="toolbar" style="margin-top:10px"><button class="btn small secondary" data-progress-goal="${g.id}">Atualizar</button></div></div>`).join(''):'<div class="panel"><p class="muted">Nenhuma meta.</p></div>'}</div>`}
function reports(){const r=db.results,g=r.reduce((a,x)=>a+(+x.tournaments||0),0),bi=r.reduce((a,x)=>a+(+x.buyins||0),0),p=r.reduce((a,x)=>a+(+x.profit||0),0),by={};r.forEach(x=>{const k=x.site||'Sem site';if(!by[k])by[k]={g:0,p:0,b:0};by[k].g+=+x.tournaments||0;by[k].p+=+x.profit||0;by[k].b+=+x.buyins||0});return `<div class="cards"><div class="card"><small>Volume</small><strong>${g}</strong></div><div class="card"><small>Profit</small><strong class="${p>=0?'good':'bad'}">${money(p)}</strong></div><div class="card"><small>ROI</small><strong>${pct(p,bi)}</strong></div><div class="card"><small>Mãos estudadas</small><strong>${db.hands.filter(x=>x.status==='done').length}</strong></div><div class="card"><small>Aulas</small><strong>${db.studies.filter(x=>x.status==='done').length}</strong></div><div class="card"><small>Leaks</small><strong>${leakData().filter(x=>x.pending>0).length}</strong></div></div><div class="grid2"><div class="panel"><h2>Por site</h2>${Object.entries(by).map(([k,v])=>`<div class="item"><b>${esc(k)}</b> · ${v.g} MTTs · ${money(v.p)} · ${pct(v.p,v.b)} ROI</div>`).join('')||'<p class="muted">Sem dados.</p>'}</div><div class="panel"><h2>Diagnóstico</h2>${diagnostic().map(x=>`<div class="notice" style="margin-bottom:8px">${x}</div>`).join('')}</div></div>`}
function diagnostic(){const o=[],pending=db.hands.filter(x=>x.status!=='done').length,total=db.results.reduce((a,x)=>a+(+x.tournaments||0),0);if(total<100)o.push('A amostra ainda é pequena; evite conclusões fortes sobre ROI.');if(pending>5)o.push(`Você tem ${pending} mãos pendentes. Crie uma sessão específica de revisão.`);const l=leakData()[0];if(l?.pending)o.push(`Tema com maior prioridade: ${esc(l.topic)} (${l.pending} pendentes).`);if(!o.length)o.push('Nenhum alerta forte no momento.');return o}
function bindPage(p){if(p==='dashboard'){periodSelect.value=String(periodDays);periodSelect.onchange=()=>{periodDays=+periodSelect.value;route('dashboard')}}if(p==='studies'){newStudy.onclick=studyModal;document.querySelectorAll('[data-toggle-study]').forEach(b=>b.onclick=()=>toggle('studies',b.dataset.toggleStudy))}if(p==='hands'){newHand.onclick=handModal;document.querySelectorAll('[data-toggle-hand]').forEach(b=>b.onclick=()=>toggle('hands',b.dataset.toggleHand));document.querySelectorAll('[data-view-hand]').forEach(b=>b.onclick=()=>viewHand(b.dataset.viewHand))}if(p==='results')newResult.onclick=resultModal;if(p==='goals'){newGoal.onclick=goalModal;document.querySelectorAll('[data-progress-goal]').forEach(b=>b.onclick=()=>goalProgress(b.dataset.progressGoal))}}
function openModal(t,h){modalTitle.textContent=t;modalBody.innerHTML=h;modal.classList.add('show')}
async function insert(t,row){const {error}=await supabase.from(t).insert({...row,user_id:user.id});if(error)return alert(error.message);await load();route(t==='studies'?'studies':t==='hands'?'hands':t==='results'?'results':'goals')}
async function toggle(t,id){const x=db[t].find(x=>x.id===id);const {error}=await supabase.from(t).update({status:x.status==='done'?'pending':'done'}).eq('id',id);if(error)alert(error.message);await load();route(t)}
function studyModal(){openModal('Nova aula',`<div class="form"><div class="field"><label>Curso</label><input id="s_course"></div><div class="field"><label>Aula</label><input id="s_title"></div><div class="field"><label>Professor</label><input id="s_teacher"></div><div class="field"><label>Tema</label><input id="s_topic"></div><div class="field"><label>Data</label><input id="s_date" type="date" value="${today()}"></div><div class="field"><label>Duração (min)</label><input id="s_duration" type="number" value="60"></div><div class="field"><label>Status</label><select id="s_status"><option value="done">Assistida</option><option value="pending">Pendente</option></select></div><div class="field"><label>Tags</label><input id="s_tags"></div><div class="field span2"><label>Anotações</label><textarea id="s_notes"></textarea></div></div><br><button class="btn" id="saveStudy">Salvar</button>`);saveStudy.onclick=()=>{if(!s_title.value.trim())return alert('Digite o nome da aula.');insert('studies',{course:s_course.value,title:s_title.value,teacher:s_teacher.value,topic:s_topic.value||'Geral',date:s_date.value,duration:+s_duration.value||0,status:s_status.value,tags:s_tags.value,notes:s_notes.value});modal.classList.remove('show')}}
function handModal(){openModal('Nova mão',`<div class="form"><div class="field"><label>Data</label><input id="h_date" type="date" value="${today()}"></div><div class="field"><label>Site</label><input id="h_site"></div><div class="field"><label>Torneio</label><input id="h_tournament"></div><div class="field"><label>Formato</label><select id="h_format"><option>PKO</option><option>MTT Regular</option><option>Satélite</option><option>Outro</option></select></div><div class="field"><label>Spot</label><input id="h_spot"></div><div class="field"><label>Tema</label><input id="h_topic"></div><div class="field"><label>Blinds</label><input id="h_blinds"></div><div class="field"><label>Stack efetivo</label><input id="h_stack"></div><div class="field"><label>Hero</label><input id="h_hero"></div><div class="field"><label>Vilão</label><input id="h_villain"></div><div class="field span2"><label>Pré-flop</label><textarea id="h_preflop"></textarea></div><div class="field span2"><label>Flop</label><textarea id="h_flop"></textarea></div><div class="field span2"><label>Turn</label><textarea id="h_turn"></textarea></div><div class="field span2"><label>River</label><textarea id="h_river"></textarea></div><div class="field span2"><label>Dúvida</label><textarea id="h_question"></textarea></div><div class="field span2"><label>Análise / solução</label><textarea id="h_notes"></textarea></div><div class="field"><label>Tags</label><input id="h_tags"></div><div class="field"><label>Imagem da mão</label><input id="h_image" type="file" accept="image/*"></div></div><br><button class="btn" id="saveHand">Salvar mão</button><p id="uploadMsg" class="muted"></p>`);saveHand.onclick=async()=>{if(!h_question.value.trim())return alert('Digite a dúvida da mão.');saveHand.disabled=true;uploadMsg.textContent='Salvando...';let image_path=null;const f=h_image.files[0];if(f){const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_');image_path=`${user.id}/${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('hand-images').upload(image_path,f);if(error){saveHand.disabled=false;uploadMsg.textContent='Erro no upload: '+error.message;return}}const row={date:h_date.value,site:h_site.value,tournament:h_tournament.value,format:h_format.value,spot:h_spot.value,topic:h_topic.value||'Geral',blinds:h_blinds.value,effective_stack:h_stack.value,hero_position:h_hero.value,villain_position:h_villain.value,preflop:h_preflop.value,flop:h_flop.value,turn:h_turn.value,river:h_river.value,question:h_question.value,notes:h_notes.value,tags:h_tags.value,status:'pending',image_path};const {error}=await supabase.from('hands').insert({...row,user_id:user.id});if(error){saveHand.disabled=false;uploadMsg.textContent=error.message;return}modal.classList.remove('show');await load();route('hands')}}
function viewHand(id){const h=db.hands.find(x=>x.id===id);openModal('Detalhes da mão',`${h.image_url?`<img src="${h.image_url}" style="width:100%;max-height:420px;object-fit:contain;border-radius:10px;background:#0c1526;margin-bottom:12px">`:''}<div class="grid2"><div class="panel"><b>${esc(h.tournament||'')}</b><p class="muted">${h.date} · ${esc(h.site||'')} · ${esc(h.format||'')}</p><p>${esc(h.spot||'')} · ${esc(h.blinds||'')} · ${esc(h.effective_stack||'')}</p><p>Hero: ${esc(h.hero_position||'')} · Vilão: ${esc(h.villain_position||'')}</p></div><div class="panel"><b>${esc(h.topic||'Geral')}</b><div>${tagList(h.tags).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><p><b>Dúvida:</b><br>${esc(h.question||'')}</p></div></div><div class="panel"><p><b>Pré-flop</b><br>${esc(h.preflop||'-')}</p><p><b>Flop</b><br>${esc(h.flop||'-')}</p><p><b>Turn</b><br>${esc(h.turn||'-')}</p><p><b>River</b><br>${esc(h.river||'-')}</p><p><b>Análise / solução</b><br>${esc(h.notes||'-')}</p></div>`)}
function resultModal(){openModal('Novo resultado',`<div class="form form3"><div class="field"><label>Data</label><input id="r_date" type="date" value="${today()}"></div><div class="field"><label>Site</label><input id="r_site"></div><div class="field"><label>Formato</label><select id="r_format"><option>PKO</option><option>MTT Regular</option><option>Satélite</option><option>Outro</option></select></div><div class="field"><label>Torneios</label><input id="r_tournaments" type="number" value="0"></div><div class="field"><label>Buy-ins ($)</label><input id="r_buyins" type="number" step=".01" value="0"></div><div class="field"><label>Prêmios ($)</label><input id="r_prizes" type="number" step=".01" value="0"></div><div class="field"><label>ITM</label><input id="r_itm" type="number" value="0"></div><div class="field"><label>FT</label><input id="r_ft" type="number" value="0"></div><div class="field"><label>Vitórias</label><input id="r_wins" type="number" value="0"></div><div class="field"><label>Horas</label><input id="r_hours" type="number" step=".1" value="0"></div></div><br><button class="btn" id="saveResult">Salvar</button>`);saveResult.onclick=()=>{const t=+r_tournaments.value||0,bi=+r_buyins.value||0,pr=+r_prizes.value||0;if(!t)return alert('Informe o número de torneios.');insert('results',{date:r_date.value,site:r_site.value,format:r_format.value,tournaments:t,buyins:bi,prizes:pr,profit:pr-bi,abi:t?bi/t:0,itm:+r_itm.value||0,ft:+r_ft.value||0,wins:+r_wins.value||0,hours:+r_hours.value||0});modal.classList.remove('show')}}
function goalModal(){openModal('Nova meta',`<div class="form"><div class="field"><label>Título</label><input id="g_title"></div><div class="field"><label>Métrica</label><select id="g_metric"><option>Volume</option><option>Estudo</option><option>Mãos revisadas</option><option>Profit</option><option>ROI</option></select></div><div class="field"><label>Meta</label><input id="g_target" type="number" step=".1"></div><div class="field"><label>Unidade</label><input id="g_unit"></div><div class="field"><label>Prazo</label><input id="g_date" type="date" value="${today()}"></div></div><br><button class="btn" id="saveGoal">Salvar</button>`);saveGoal.onclick=()=>{if(!g_title.value.trim())return alert('Digite o título da meta.');insert('goals',{title:g_title.value,metric:g_metric.value,target_value:+g_target.value||0,current_value:0,unit:g_unit.value,date:g_date.value});modal.classList.remove('show')}}
async function goalProgress(id){const g=db.goals.find(x=>x.id===id),v=prompt(`Valor atual (${g.unit||''})`,g.current_value||0);if(v===null)return;const {error}=await supabase.from('goals').update({current_value:+v||0}).eq('id',id);if(error)alert(error.message);await load();route('goals')}
supabase.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;if(user){await load();shell()}else loginView()})
const {data:s}=await supabase.auth.getSession();user=s.session?.user||null;if(user){await load();shell()}else loginView()
